-- This file is autogenerated (edit palettes/dusk.ini to change)
return {
  bg0     = "#1c1b22",
  bg1     = "#242330",
  bg2     = "#2c2b38",
  bg3     = "#383646",
  bg4     = "#504e5e",

  fg0     = "#DCD7BA",
  fg1     = "#C8C093",
  fg2     = "#9a8f78",
  fg3     = "#635c4e",

  red     = "#e07070",
  orange  = "#e8985a",
  yellow  = "#d4b870",
  green   = "#8ec47a",
  cyan    = "#5ecfcf",
  blue    = "#7bb0e8",
  purple  = "#b8a0e0",
  pink    = "#e88a7a",

  err     = "#e07070",
  warn    = "#d4b870",
  info    = "#5ecfcf",
  hint    = "#8ec47a",
  added   = "#8ec47a",
  changed = "#e8985a",
  removed = "#e07070",

  none    = "NONE",
}
