# Kitty terminal theme
# https://sw.kovidgoyal.net/kitty/conf/#color-scheme

background              #1f1e1c
foreground              #C8C093
selection_background    #3b3835
selection_foreground    #DCD7BA
cursor                  #C8C093
cursor_text_color       #1f1e1c
url_color               #889e80

# Tabs
active_tab_background   #1f1e1c
active_tab_foreground   #DCD7BA
inactive_tab_background #2f2d2a
inactive_tab_foreground #6a5f50
tab_bar_background      #272523

# Marks
mark1_background        #3b3835
mark1_foreground        #DCD7BA
mark2_background        #a86858
mark2_foreground        #1f1e1c
mark3_background        #889e80
mark3_foreground        #1f1e1c

# Black
color0  #1f1e1c
color8  #524e49

# Red
color1  #a86858
color9  #a86858

# Green
color2  #889e80
color10 #889e80

# Yellow
color3  #b8a070
color11 #b8a070

# Blue
color4  #889e80
color12 #889e80

# Magenta / Purple
color5  #a86858
color13 #a86858

# Cyan
color6  #889e80
color14 #889e80

# White
color7  #C8C093
color15 #DCD7BA
