# Mokka — kitty terminal theme
# https://sw.kovidgoyal.net/kitty/conf/#color-scheme

background              #1c1b22
foreground              #C8C093
selection_background    #383646
selection_foreground    #DCD7BA
cursor                  #C8C093
cursor_text_color       #1c1b22
url_color               #7bb0e8

# Tabs
active_tab_background   #1c1b22
active_tab_foreground   #DCD7BA
inactive_tab_background #2c2b38
inactive_tab_foreground #635c4e
tab_bar_background      #242330

# Marks
mark1_background        #383646
mark1_foreground        #DCD7BA
mark2_background        #b8a0e0
mark2_foreground        #1c1b22
mark3_background        #82afa0
mark3_foreground        #1c1b22

# Black
color0  #1c1b22
color8  #504e5e

# Red
color1  #e07070
color9  #e07070

# Green
color2  #8ec47a
color10 #8ec47a

# Yellow
color3  #d4b870
color11 #d4b870

# Blue
color4  #7bb0e8
color12 #7bb0e8

# Magenta / Purple
color5  #b8a0e0
color13 #e88a7a

# Cyan
color6  #82afa0
color14 #82afa0

# White
color7  #C8C093
color15 #DCD7BA
