# Mokka — kitty terminal theme
# https://sw.kovidgoyal.net/kitty/conf/#color-scheme

background              #110e0d
foreground              #C8C093
selection_background    #281e1b
selection_foreground    #DCD7BA
cursor                  #C8C093
cursor_text_color       #110e0d
url_color               #82aacc

# Tabs
active_tab_background   #110e0d
active_tab_foreground   #DCD7BA
inactive_tab_background #1f1714
inactive_tab_foreground #6a5248
tab_bar_background      #181210

# Marks
mark1_background        #281e1b
mark1_foreground        #DCD7BA
mark2_background        #c792d0
mark2_foreground        #110e0d
mark3_background        #8db49e
mark3_foreground        #110e0d

# Black
color0  #110e0d
color8  #3d2e29

# Red
color1  #e06c75
color9  #e06c75

# Green
color2  #98c379
color10 #98c379

# Yellow
color3  #ddc98a
color11 #ddc98a

# Blue
color4  #82aacc
color12 #82aacc

# Magenta / Purple
color5  #c792d0
color13 #f0836e

# Cyan
color6  #8db49e
color14 #8db49e

# White
color7  #C8C093
color15 #DCD7BA
