# Mokka — kitty terminal theme
# https://sw.kovidgoyal.net/kitty/conf/#color-scheme

background              #171d18
foreground              #C8C093
selection_background    #303d32
selection_foreground    #DCD7BA
cursor                  #C8C093
cursor_text_color       #171d18
url_color               #82aacc

# Tabs
active_tab_background   #171d18
active_tab_foreground   #DCD7BA
inactive_tab_background #252f27
inactive_tab_foreground #5c5c48
tab_bar_background      #1e2620

# Marks
mark1_background        #303d32
mark1_foreground        #DCD7BA
mark2_background        #c792d0
mark2_foreground        #171d18
mark3_background        #6ec4b0
mark3_foreground        #171d18

# Black
color0  #171d18
color8  #475248

# Red
color1  #e06c75
color9  #e06c75

# Green
color2  #a7c97a
color10 #a7c97a

# Yellow
color3  #e5c07b
color11 #e5c07b

# Blue
color4  #82aacc
color12 #82aacc

# Magenta / Purple
color5  #c792d0
color13 #f0836e

# Cyan
color6  #6ec4b0
color14 #6ec4b0

# White
color7  #C8C093
color15 #DCD7BA
