# Mokka — kitty terminal theme
# https://sw.kovidgoyal.net/kitty/conf/#color-scheme

background              #1c1b19
foreground              #C8C093
selection_background    #363430
selection_foreground    #DCD7BA
cursor                  #C8C093
cursor_text_color       #1c1b19
url_color               #82aacc

# Tabs
active_tab_background   #1c1b19
active_tab_foreground   #DCD7BA
inactive_tab_background #2a2927
inactive_tab_foreground #6a5f50
tab_bar_background      #232220

# Marks
mark1_background        #363430
mark1_foreground        #DCD7BA
mark2_background        #c792d0
mark2_foreground        #1c1b19
mark3_background        #7ec8c8
mark3_foreground        #1c1b19

# Black
color0  #1c1b19
color8  #4e4b46

# Red
color1  #e06c75
color9  #e06c75

# Green
color2  #98c379
color10 #98c379

# Yellow
color3  #e5c07b
color11 #e5c07b

# Blue
color4  #82aacc
color12 #82aacc

# Magenta / Purple
color5  #c792d0
color13 #f0836e

# Cyan
color6  #7ec8c8
color14 #7ec8c8

# White
color7  #C8C093
color15 #DCD7BA
